### ISSUE TITLE
change screensaver 

### ISSUE THREAD

**Issue by bryan-brancotte** [cyclone-project/cyclone-python-pam#19]
m6502 have been observed to consum a lot of cpu
Solution found at 
https://ubuntuforums.org/showthread.php?t=2326719

> Edit this file: /etc/X11/Xresources/x11-common
> 
> Add this line to the bottom:
> `xscreensaver.mode: blank`

Not tested in ubuntu yet.

How can we apply it on centos ?

**Comment by Sturgelose** [comment]
In CentOS, I'm still checking how to use this X11 setup... I have to check how to install xPra as well..
