### ISSUE TITLE
Edugain in keycloack not displaying the list of providers

### ISSUE THREAD

**Issue by bryan-brancotte** [cyclone-project/cyclone-python-pam#7]
I go to 
https://federation.cyclone-project.eu/auth/realms/master/protocol/openid-connect/auth?client_id=test&redirect_uri=http://192.54.201.184:80/sso_callback&response_type=code
and then click on edugain, the list of provider is not displayed anymore.

**Comment by omer-ilhan** [comment]
Hi,

is it not loading at all or are you seeing an empty list?

Also: Does the error persist? We restart the services from time to time which may leave the list temporarily empty.

**Comment by bryan-brancotte** [comment]
Hi,
I see an empty list, i would have gave you a screen shot, but now i just see a "500 - Internal Server Error" on the keycloack page, before being able to clic on edugain button
